### ISSUE TITLE
uninformative errors in isotropic_powerspectrum

### ISSUE THREAD

**Issue by rabernat** [rabernat/xrft#12]
`isotropic_powerspectrum` only works when transforming over two dimensions. But the errors raised are not informative when we specify other dimensions.

Consider an example 2D dataset:
```python
da = xr.DataArray(np.random.rand(20,30), dims=['y', 'x'],
              coords={'y': np.arange(20), 'x': np.arange(30)})
```
If I try to take an isotropic spectrum of just one dimension of this, i.e. `xrft.isotropic_powerspectrum(da[0])`, I get the error
```
IndexError                                Traceback (most recent call last)
<ipython-input-41-702d2e01fc3e> in <module>()
----> 1 xrft.isotropic_powerspectrum(da[0])

/Users/rpa/RND/Public/xrft/xrft/xrft.py in isotropic_powerspectrum(da, dim, shift, remove_mean, density, window, nbins)
    314 
    315     k = ps[ps.dims[0]].values
--> 316     l = ps[ps.dims[1]].values
    317 
    318     kr, iso_ps = _azimuthal_avg(k, l, ps, nbins=nbins)

IndexError: tuple index out of range
```

Conversely, if I specify a single dimension, i.e. `xrft.isotropic_powerspectrum(da, dim=['x'])`, it does not produce an error. I'm not sure what is actually being calculated in this case.

I think the desired behavior is the following. If `dim` is not specified, automatically use the _last two dimensions_. If `dim` is specified, make sure it is of length 2. If the array has fewer than two dimensions, raise an error.

**Comment by roxyboy** [comment]
I changed the error message in the newest pull request.
